import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/app/index.ts",
    "src/components/index.ts",
    "src/services/index.ts",
    "src/types/index.ts",
    "src/config.ts",
  ],

  format: ["cjs", "esm"],

  // Types are better generated by tsc build mode (tsconfig.build.json),
  // so here we just build JS bundles
  dts: false,

  splitting: false,
  sourcemap: false,
  clean: true,

  external: ["react", "react-dom", "@captify-io/platform"],
});
